//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magma.WCF.Services.Loftware.Tester.LoftwareService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsRowPrintStatus", Namespace="http://schemas.datacontract.org/2004/07/Assembly.Software.Loftware")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magma.WCF.Services.Loftware.Tester.LoftwareService.clsLoftwareServerServerStatusType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magma.WCF.Services.Loftware.Tester.LoftwareService.clsPrinter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magma.WCF.Services.Loftware.Tester.LoftwareService.clsPrinter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magma.WCF.Services.Loftware.Tester.LoftwareService.LLMStatusCodes))]
    public partial class clsRowPrintStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Magma.WCF.Services.Loftware.Tester.LoftwareService.LLMStatusCodes PrintedJobStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] SubmitedDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitedXmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magma.WCF.Services.Loftware.Tester.LoftwareService.LLMStatusCodes PrintedJobStatus {
            get {
                return this.PrintedJobStatusField;
            }
            set {
                if ((this.PrintedJobStatusField.Equals(value) != true)) {
                    this.PrintedJobStatusField = value;
                    this.RaisePropertyChanged("PrintedJobStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] SubmitedData {
            get {
                return this.SubmitedDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitedDataField, value) != true)) {
                    this.SubmitedDataField = value;
                    this.RaisePropertyChanged("SubmitedData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmitedXml {
            get {
                return this.SubmitedXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitedXmlField, value) != true)) {
                    this.SubmitedXmlField = value;
                    this.RaisePropertyChanged("SubmitedXml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsLoftwareServer.ServerStatusType", Namespace="http://schemas.datacontract.org/2004/07/Assembly.Software.Loftware")]
    public enum clsLoftwareServerServerStatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsPrinter", Namespace="http://schemas.datacontract.org/2004/07/Assembly.Software.Loftware")]
    [System.SerializableAttribute()]
    public partial class clsPrinter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrinterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterPortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrinterAlias {
            get {
                return this.PrinterAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterAliasField, value) != true)) {
                    this.PrinterAliasField = value;
                    this.RaisePropertyChanged("PrinterAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrinterName {
            get {
                return this.PrinterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterNameField, value) != true)) {
                    this.PrinterNameField = value;
                    this.RaisePropertyChanged("PrinterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrinterNumber {
            get {
                return this.PrinterNumberField;
            }
            set {
                if ((this.PrinterNumberField.Equals(value) != true)) {
                    this.PrinterNumberField = value;
                    this.RaisePropertyChanged("PrinterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrinterPort {
            get {
                return this.PrinterPortField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterPortField, value) != true)) {
                    this.PrinterPortField = value;
                    this.RaisePropertyChanged("PrinterPort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LLMStatusCodes", Namespace="http://schemas.datacontract.org/2004/07/Loftware.Common")]
    public enum LLMStatusCodes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CriticalFailure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceError = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoftwareService.ILoftwareService")]
    public interface ILoftwareService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/PrintLabelHashtable", ReplyAction="http://tempuri.org/ILoftwareService/PrintLabelHashtableResponse")]
        Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[] PrintLabelHashtable(int intPrinterID, string strLabelName, int intSerializedLabels, int intNumberOfCopies, System.Collections.Generic.Dictionary<object, object> htlParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/PrintLabelDatatable", ReplyAction="http://tempuri.org/ILoftwareService/PrintLabelDatatableResponse")]
        Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[] PrintLabelDatatable(int intPrinterID, string strLabelName, int intSerializedLabels, int intNumberOfCopies, System.Data.DataTable dtlParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/PrintLabelDictionary", ReplyAction="http://tempuri.org/ILoftwareService/PrintLabelDictionaryResponse")]
        Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[] PrintLabelDictionary(int intPrinterID, string strLabelName, int intSerializedLabels, int intNumberOfCopies, System.Collections.Generic.Dictionary<string, string> dictParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/GetServerStatus", ReplyAction="http://tempuri.org/ILoftwareService/GetServerStatusResponse")]
        Magma.WCF.Services.Loftware.Tester.LoftwareService.clsLoftwareServerServerStatusType GetServerStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/GetPrintersList", ReplyAction="http://tempuri.org/ILoftwareService/GetPrintersListResponse")]
        Magma.WCF.Services.Loftware.Tester.LoftwareService.clsPrinter[] GetPrintersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/GetLabelsList", ReplyAction="http://tempuri.org/ILoftwareService/GetLabelsListResponse")]
        string[] GetLabelsList(string strFolderLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoftwareService/GetLabelFields", ReplyAction="http://tempuri.org/ILoftwareService/GetLabelFieldsResponse")]
        System.Collections.Generic.Dictionary<string, int> GetLabelFields(string strFolderName, string strLabelName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoftwareServiceChannel : Magma.WCF.Services.Loftware.Tester.LoftwareService.ILoftwareService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoftwareServiceClient : System.ServiceModel.ClientBase<Magma.WCF.Services.Loftware.Tester.LoftwareService.ILoftwareService>, Magma.WCF.Services.Loftware.Tester.LoftwareService.ILoftwareService {
        
        public LoftwareServiceClient() {
        }
        
        public LoftwareServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoftwareServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoftwareServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoftwareServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[] PrintLabelHashtable(int intPrinterID, string strLabelName, int intSerializedLabels, int intNumberOfCopies, System.Collections.Generic.Dictionary<object, object> htlParams) {
            return base.Channel.PrintLabelHashtable(intPrinterID, strLabelName, intSerializedLabels, intNumberOfCopies, htlParams);
        }
        
        public Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[] PrintLabelDatatable(int intPrinterID, string strLabelName, int intSerializedLabels, int intNumberOfCopies, System.Data.DataTable dtlParams) {
            return base.Channel.PrintLabelDatatable(intPrinterID, strLabelName, intSerializedLabels, intNumberOfCopies, dtlParams);
        }
        
        public Magma.WCF.Services.Loftware.Tester.LoftwareService.clsRowPrintStatus[] PrintLabelDictionary(int intPrinterID, string strLabelName, int intSerializedLabels, int intNumberOfCopies, System.Collections.Generic.Dictionary<string, string> dictParams) {
            return base.Channel.PrintLabelDictionary(intPrinterID, strLabelName, intSerializedLabels, intNumberOfCopies, dictParams);
        }
        
        public Magma.WCF.Services.Loftware.Tester.LoftwareService.clsLoftwareServerServerStatusType GetServerStatus() {
            return base.Channel.GetServerStatus();
        }
        
        public Magma.WCF.Services.Loftware.Tester.LoftwareService.clsPrinter[] GetPrintersList() {
            return base.Channel.GetPrintersList();
        }
        
        public string[] GetLabelsList(string strFolderLocation) {
            return base.Channel.GetLabelsList(strFolderLocation);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetLabelFields(string strFolderName, string strLabelName) {
            return base.Channel.GetLabelFields(strFolderName, strLabelName);
        }
    }
}
